---
abstract: 'Load CSV as config files'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Any-CSV
provides:
  Config::Any::CSV:
    file: lib/Config/Any/CSV.pm
    version: 0.05
requires:
  Config::Any: 0
  Text::CSV: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/nichtich/Config-Any-CSV/issues
  homepage: https://github.com/nichtich/Config-Any-CSV
  repository: https://github.com/nichtich/Config-Any-CSV.git
version: 0.05
